<?php
$surahOptions = array();
foreach (rows('SELECT name, verses, juz FROM surahs ORDER BY CASE WHEN surah_number IS NULL OR surah_number = 0 THEN 1 ELSE 0 END, juz, surah_number') as $surah) {
    $surahOptions[$surah['name']] = $surah['name'] . ' — ' . $surah['verses'] . ' ayat' . ((int)$surah['juz'] > 0 ? ' (Juz ' . $surah['juz'] . ')' : '');
}

$formFields=[
'student'=>[['name','Nama lengkap santri','text'],['nickname','Nama panggilan','text'],['birth_date','Tanggal lahir','date'],['gender','Jenis kelamin','select',['L'=>'Laki-laki','P'=>'Perempuan']],['address','Alamat','text'],['halaqoh_id','Halaqoh','db',rows('SELECT id,name FROM halaqoh')],['guardian_name','Nama wali','text'],['guardian_phone','Kontak WhatsApp','text'],['email','Email login wali','email'],['login_password','Kata sandi akun wali','password']],
'teacher'=>[['name','Nama ustadzah','text'],['address','Alamat','text'],['email','Email login','email'],['phone','Kontak','text'],['login_password','Kata sandi akun','password']],
'halaqoh'=>[['name','Nama Halaqoh','text'],['level','Tingkat','select',['Tingkat Dasar'=>'Tingkat Dasar','Tingkat Menengah'=>'Tingkat Menengah','Tingkat Atas'=>'Tingkat Atas']],['surah_ids','Cakupan Surat','multidb',rows('SELECT id,name,juz,surah_number FROM surahs ORDER BY CASE WHEN surah_number IS NULL OR surah_number = 0 THEN 1 ELSE 0 END, juz, surah_number')],['teacher_id','Ustadzah Pembimbing','db',rows('SELECT id,name FROM teachers')]],
'category'=>[['name','Nama kategori','text']],
'indicator'=>[['category_id','Kategori','db',rows('SELECT id,name FROM categories')],['name','Nama indikator','text'],['description','Deskripsi','textarea']],
'surah'=>[['name','Nama surah','text'],['verses','Jumlah ayat','number'],['juz','Juz','number']],
'assessment'=>[['student_id','Santri','db',rows('SELECT id,name FROM students')],['teacher_id','Ustadzah','db',rows('SELECT id,name FROM teachers')],['date','Tanggal','date'],['surah','Surah','select',$surahOptions],['verse_range','Rentang ayat','text'],['memorization','Nilai hafalan','number'],['murojaah',"Nilai muroja'ah",'number'],['status','Status','select',['Lancar'=>'Lancar','Kurang Lancar'=>'Kurang Lancar','Ulangi'=>'Ulangi']],['message','Pesan ustadzah','textarea']]
]; $fields=$formFields[$entity]; ?>
<?php if ($entity === 'assessment') { include __DIR__ . '/forms/assessment.php'; return; } ?>
<div class="modal" id="formModal"><div class="modal-box form-modal"><div class="modal-head"><div><p class="eyebrow green">Formulir</p><h3 id="formTitle">Tambah <?=e($pageMeta['title'])?></h3></div><button type="button" onclick="closeModal('formModal')">×</button></div><?php if($entity==='student'):?><div class="form-steps"><button type="button" class="active" data-step-button="1"><span>1</span>Data Santri</button><i></i><button type="button" data-step-button="2"><span>2</span>Data Wali Santri</button></div><?php endif?><form method="post" id="dataForm" class="form-grid" data-entity="<?=e($entity)?>"><input type="hidden" name="csrf" value="<?=csrf()?>"><input type="hidden" name="action" value="save"><input type="hidden" name="entity" value="<?=e($entity)?>"><input type="hidden" name="return" value="<?=e($page)?>"><input type="hidden" name="id" id="recordId">
<?php $guardianFields=['guardian_name','guardian_phone','email','login_password'];foreach($fields as $f):[$name,$label,$type]=$f;$optional=$name==='login_password';$step=$entity==='student'&&in_array($name,$guardianFields,true)?2:1;$stepClass=$entity==='student'?'step-field'.($step===1?' step-visible':''):'';?><label class="<?=$type==='textarea'||$type==='multidb'?'full ':''?><?=$stepClass?>" <?=$entity==='student'?'data-form-step="'.$step.'"':''?>><?=e($label)?><?php if($type==='select'||$type==='db'):?><select name="<?=e($name)?>" data-field="<?=e($name)?>" required><option value="">Pilih <?=strtolower(e($label))?></option><?php foreach($f[3] as $k=>$v):$value=$type==='db'?$v['id']:$k;$text=$type==='db'?$v['name']:$v;?><option value="<?=e($value)?>"><?=e($text)?></option><?php endforeach?></select><?php elseif($type==='multidb'):?><select name="<?=e($name)?>[]" data-field="<?=e($name)?>" multiple size="8" required><?php foreach($f[3] as $v):?><option value="<?=e($v['id'])?>"><?=isset($v['juz'])?'Juz '.e($v['juz']).' • ':''?><?=isset($v['surah_number'])&&$v['surah_number']?'No. '.e($v['surah_number']).' — ':''?><?=e($v['name'])?></option><?php endforeach?></select><span class="selection-hint"><span class="selection-hint-icon" aria-hidden="true">i</span><span><b>Diurutkan berdasarkan Juz dan nomor surat.</b><small>Pilih satu atau beberapa surat. Di komputer, tahan tombol <kbd>Ctrl</kbd> saat memilih.</small></span></span><?php elseif($type==='textarea'):?><textarea name="<?=e($name)?>" data-field="<?=e($name)?>" rows="3" required></textarea><?php else:?><input type="<?=e($type)?>" name="<?=e($name)?>" data-field="<?=e($name)?>" <?=in_array($name,['memorization','murojaah'],true)?'min="0" max="50"':''?> <?=$optional?'placeholder="Opsional"':'required'?>><?php endif?><?=$optional?'<small class="field-help">Kosongkan untuk memakai password default: <b>'.e(DEFAULT_ACCOUNT_PASSWORD).'</b></small>':''?></label><?php endforeach?><div class="form-actions full"><button type="button" class="btn ghost" onclick="closeModal('formModal')">Batal</button><?php if($entity==='student'):?><button type="button" class="btn secondary student-back" onclick="showStudentStep(1)">Kembali</button><button type="button" class="btn primary student-next" onclick="showStudentStep(2)">Selanjutnya →</button><?php endif?><button class="btn primary form-submit">Simpan data</button></div></form></div></div>
