<?php
$currentTeacher = user()['role'] === 'ustadzah' ? row('SELECT id, name FROM teachers WHERE user_id = ?', array(user()['id'])) : null;
$studentSql = 'SELECT s.id, s.name, h.name AS halaqoh, t.id AS teacher_id, t.name AS teacher_name FROM students s LEFT JOIN halaqoh h ON h.id = s.halaqoh_id LEFT JOIN teachers t ON t.id = h.teacher_id';
$studentParams = array();
if (user()['role'] === 'ustadzah') {
    if ($currentTeacher) { $studentSql .= ' WHERE h.teacher_id = ?'; $studentParams[] = $currentTeacher['id']; }
    else { $studentSql .= ' WHERE 1 = 0'; }
}
$studentSql .= ' ORDER BY s.name';
$studentsForAssessment = rows($studentSql, $studentParams);
$surahsForAssessment = rows('SELECT s.name, s.verses, COALESCE((SELECT GROUP_CONCAT(sj.juz) FROM surah_juz sj WHERE sj.surah_id = s.id), s.juz) AS juz FROM surahs s ORDER BY CASE WHEN s.surah_number IS NULL OR s.surah_number = 0 THEN 1 ELSE 0 END, s.juz, s.surah_number');
$hafalanIndicators = rows("SELECT i.id, i.name FROM indicators i JOIN categories c ON c.id = i.category_id WHERE c.name = 'Hafalan' ORDER BY i.id");
$murojaahIndicators = rows("SELECT i.id, i.name FROM indicators i JOIN categories c ON c.id = i.category_id WHERE c.name LIKE 'Muroja%' ORDER BY i.id");
$additionalCategories = rows("SELECT c.id, c.name FROM categories c WHERE c.name <> 'Hafalan' AND c.name NOT LIKE 'Muroja%' AND EXISTS (SELECT 1 FROM indicators i WHERE i.category_id = c.id) ORDER BY c.id");
$characterAspects = array('Kedisiplinan', 'Akhlak', 'Kejujuran', 'Ketekunan');
?>
<div class="modal" id="formModal">
    <div class="modal-box assessment-modal">
        <div class="modal-head"><div><p class="eyebrow green">Formulir Penilaian</p><h3 id="formTitle">Tambah Penilaian Santri</h3></div><button type="button" onclick="closeModal('formModal')">×</button></div>
        <form method="post" id="dataForm" class="assessment-form" data-entity="assessment" data-default-student-id="<?= isset($historyStudentId) ? (int) $historyStudentId : '' ?>">
            <input type="hidden" name="csrf" value="<?= csrf() ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="entity" value="assessment"><input type="hidden" name="return" value="assessments"><input type="hidden" name="id" id="recordId" value="">
            <aside class="assessment-formula"><div><b>Perhitungan Nilai Otomatis</b><span>Nilai kategori = rata-rata seluruh indikator. Nilai akhir = (Nilai Hafalan + Nilai Murojaah) ÷ 2.</span></div><div class="formula-ranges"><span><i class="green"></i><b>80–100</b> Lancar</span><span><i class="yellow"></i><b>65–79</b> Kurang Lancar</span><span><i class="red"></i><b>0–64</b> Ulangi</span></div></aside>
            <section class="assessment-block"><div class="assessment-block-title"><span>1</span><div><h4>Informasi Penilaian</h4><p>Pilih santri; Halaqoh dan Ustadzah penilai akan terisi otomatis.</p></div></div><div class="assessment-fields three"><label>Nama Santri<select name="student_id" id="assessmentStudent" required><option value="">Pilih santri</option><?php foreach($studentsForAssessment as $student):?><option value="<?= (int)$student['id'] ?>" data-halaqoh="<?= e($student['halaqoh']) ?>" data-teacher-id="<?= (int)$student['teacher_id'] ?>" data-teacher-name="<?= e($student['teacher_name']) ?>"><?= e($student['name']) ?></option><?php endforeach?></select></label><label>Halaqoh<input type="text" id="assessmentHalaqoh" placeholder="Terisi otomatis" readonly></label><label>Ustadzah Penilai<input type="text" id="assessmentTeacher" value="<?= e($currentTeacher ? $currentTeacher['name'] : '') ?>" placeholder="Terisi otomatis" readonly><input type="hidden" name="teacher_id" id="assessmentTeacherId" value="<?= (int)($currentTeacher ? $currentTeacher['id'] : 0) ?>"></label><label>Tanggal Penilaian<input type="date" name="date" value="<?= date('Y-m-d') ?>" required></label></div></section>
            <div class="assessment-columns">
                <section class="assessment-block"><div class="assessment-block-title"><span>2</span><div><h4>Penilaian Hafalan</h4><p>Setoran hafalan baru atau ziyadah.</p></div></div><div class="assessment-fields"><label>Surah<select name="surah" id="assessmentSurah" required><option value="">Pilih surah</option><?php foreach($surahsForAssessment as $surah):?><option value="<?= e($surah['name']) ?>" data-verses="<?= (int)$surah['verses'] ?>"><?= e($surah['name']) ?> — <?= (int)$surah['verses'] ?> ayat</option><?php endforeach?></select></label><div class="field-pair"><label>Ayat Awal<input type="number" name="verse_start" min="1" required></label><label>Ayat Akhir<input type="number" name="verse_end" min="1" id="verseEnd" required></label></div></div><div class="score-list"><div class="score-head"><span>Indikator</span><span>Nilai 0–100</span></div><?php foreach($hafalanIndicators as $indicator):?><label><span><?= e($indicator['name']) ?></span><input type="number" name="hafalan_scores[<?= (int)$indicator['id'] ?>]" min="0" max="100" required placeholder="0"></label><?php endforeach?></div></section>
                <section class="assessment-block"><div class="assessment-block-title"><span>3</span><div><h4>Penilaian Murojaah</h4><p>Pilih Juz terlebih dahulu, kemudian tentukan rentang surat yang dimurojaah.</p></div></div><div class="assessment-fields"><label>Juz Murojaah<select name="murojaah_juz" id="murojaahJuz" required><option value="">Pilih juz</option><?php foreach(range(1,30) as $juz):?><option value="<?=$juz?>">Juz <?=$juz?></option><?php endforeach?></select></label><label>Surah Awal<select name="murojaah_start" id="murojaahStart" required disabled><option value="">Pilih Juz terlebih dahulu</option><?php foreach($surahsForAssessment as $surah):?><option value="<?= e($surah['name']) ?>" data-juz="<?=e($surah['juz'])?>"><?= e($surah['name']) ?></option><?php endforeach?></select></label><label>Surah Akhir<select name="murojaah_end" id="murojaahEnd" required disabled><option value="">Pilih Juz terlebih dahulu</option><?php foreach($surahsForAssessment as $surah):?><option value="<?= e($surah['name']) ?>" data-juz="<?=e($surah['juz'])?>"><?= e($surah['name']) ?></option><?php endforeach?></select></label></div><div class="score-list"><div class="score-head"><span>Indikator</span><span>Nilai 0–100</span></div><?php foreach($murojaahIndicators as $indicator):?><label><span><?= e($indicator['name']) ?></span><input type="number" name="murojaah_scores[<?= (int)$indicator['id'] ?>]" min="0" max="100" required placeholder="0"></label><?php endforeach?></div></section>
            </div>
            <?php $sectionNumber=4;foreach($additionalCategories as $category):$categoryIndicators=rows('SELECT id,name FROM indicators WHERE category_id=? ORDER BY id',array($category['id']));?><section class="assessment-block dynamic-category"><div class="assessment-block-title"><span><?=$sectionNumber++?></span><div><h4>Penilaian <?=e($category['name'])?></h4><p>Isi nilai setiap indikator pada kategori <?=e($category['name'])?>.</p></div></div><div class="score-list"><div class="score-head"><span>Indikator</span><span>Nilai 0–100</span></div><?php foreach($categoryIndicators as $indicator):?><label><span><?=e($indicator['name'])?></span><input type="number" name="category_scores[<?=(int)$category['id']?>][<?=(int)$indicator['id']?>]" min="0" max="100" required placeholder="0"></label><?php endforeach?></div></section><?php endforeach?>
            <section class="assessment-block"><div class="assessment-block-title"><span><?=$sectionNumber++?></span><div><h4>Penilaian Karakter</h4><p>Pilih satu capaian untuk setiap aspek.</p></div></div><div class="character-table"><div class="character-row heading"><b>Aspek</b><b>Sangat Baik</b><b>Baik</b><b>Perlu Bimbingan</b></div><?php foreach($characterAspects as $index=>$aspect):?><div class="character-row"><span><?=e($aspect)?></span><?php foreach(['SB','B','KB'] as $grade):?><label><input type="radio" name="characters[<?=e($aspect)?>]" value="<?=$grade?>" <?=$grade==='B'?'checked':''?>><i></i></label><?php endforeach?></div><?php endforeach?></div></section>
            <section class="assessment-block"><div class="assessment-block-title"><span><?=$sectionNumber?></span><div><h4>Catatan Ustadzah</h4><p>Tulis apresiasi dan hal yang perlu ditingkatkan.</p></div></div><label class="assessment-note"><textarea name="message" rows="4" placeholder="Contoh: Hafalan berkembang baik. Pertahankan murojaah dan perhatikan panjang pendek bacaan." required></textarea></label></section>
            <div class="assessment-submit"><button type="button" class="btn ghost" onclick="closeModal('formModal')">Batal</button><button class="btn primary" type="submit">Simpan Penilaian</button></div>
        </form>
    </div>
</div>
